version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: pokewave-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # PostgreSQL for future use
  postgres:
    image: postgres:15-alpine
    container_name: pokewave-db
    environment:
      POSTGRES_USER: pokewave
      POSTGRES_PASSWORD: pokewave_password
      POSTGRES_DB: pokewave
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: